// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: card.sql

package maindb

import (
	"context"
	"database/sql"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (deck_id, english, russian, association, example, transcription, image, image_url, audio, audio_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, deck_id, english, russian, association, example, transcription, image, image_url, audio, audio_url, created_at
`

type CreateCardParams struct {
	DeckID        int32
	English       string
	Russian       string
	Association   sql.NullString
	Example       sql.NullString
	Transcription sql.NullString
	Image         sql.NullString
	ImageUrl      sql.NullString
	Audio         sql.NullString
	AudioUrl      sql.NullString
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (*Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.DeckID,
		arg.English,
		arg.Russian,
		arg.Association,
		arg.Example,
		arg.Transcription,
		arg.Image,
		arg.ImageUrl,
		arg.Audio,
		arg.AudioUrl,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.English,
		&i.Russian,
		&i.Association,
		&i.Example,
		&i.Transcription,
		&i.Image,
		&i.ImageUrl,
		&i.Audio,
		&i.AudioUrl,
		&i.CreatedAt,
	)
	return &i, err
}

const getCards = `-- name: GetCards :many
SELECT id, deck_id, english, russian, association, example, transcription, image, image_url, audio, audio_url, created_at FROM cards
WHERE deck_id = $1
`

func (q *Queries) GetCards(ctx context.Context, deckID int32) ([]*Card, error) {
	rows, err := q.db.QueryContext(ctx, getCards, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.English,
			&i.Russian,
			&i.Association,
			&i.Example,
			&i.Transcription,
			&i.Image,
			&i.ImageUrl,
			&i.Audio,
			&i.AudioUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
