// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package maindb

import (
	"time"

	"github.com/4kord/english-flashcards/pkg/null"
)

type Card struct {
	ID            int32
	DeckID        int32
	English       string
	Russian       string
	Association   null.String
	Example       null.String
	Transcription null.String
	Image         null.String
	ImageUrl      null.String
	Audio         null.String
	AudioUrl      null.String
	CreatedAt     time.Time
}

type Deck struct {
	ID        int32
	UserID    int32
	Name      string
	Amount    int32
	IsPremade bool
	CreatedAt time.Time
}

type Progress struct {
	ID           int32
	CardID       int32
	UserID       int32
	Learned      bool
	Selected     bool
	Correct      int32
	Incorrect    int32
	LastViewedAt time.Time
}

type Session struct {
	ID           int32
	RefreshToken string
	UserAgent    string
	UserID       int32
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type User struct {
	ID        int32
	Email     string
	Password  string
	Admin     bool
	CreatedAt time.Time
}
