// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package maindb

import (
	"context"
)

type Querier interface {
	CopyCard(ctx context.Context, arg CopyCardParams) error
	CountSessions(ctx context.Context, userID int32) (int64, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (*Card, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (*Deck, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeckAmountDownByCard(ctx context.Context, id int32) error
	DeckAmountUp(ctx context.Context, id int32) error
	DeleteCard(ctx context.Context, id int32) error
	DeleteDeck(ctx context.Context, id int32) error
	DeleteOldestSession(ctx context.Context) error
	DeleteSession(ctx context.Context, id int32) error
	DeleteSessionByToken(ctx context.Context, refreshToken string) error
	DeleteUser(ctx context.Context, id int32) error
	EditCard(ctx context.Context, arg EditCardParams) (*Card, error)
	EditDeck(ctx context.Context, arg EditDeckParams) (*Deck, error)
	GetCard(ctx context.Context, id int32) (*Card, error)
	GetCards(ctx context.Context, deckID int32) ([]*Card, error)
	GetDecks(ctx context.Context, userID int32) ([]*Deck, error)
	GetPremadeDecks(ctx context.Context) ([]*Deck, error)
	GetSession(ctx context.Context, id int32) (*Session, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (*Session, error)
	GetUser(ctx context.Context, id int32) (*User, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUsers(ctx context.Context) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
